### ISSUE TITLE
扩展可以添加多一些自定义的路径吗

### ISSUE THREAD

**Issue by Tgkkez** [goldli/EdgeDownload#1]
目前能自定义的路径的总共有6个类型的选项，我需要添加更多的规则，可以再更新一下吗

**Comment by goldli** [comment]
scripts/background.js  27行

scripts/background.js
	saveUserInput(...)
	loadSettings(...)

options.html 149行之后
可以通过修改上述几个地方来实现

**Comment by Tgkkez** [comment]
谢谢，已经修改成功了。

第二个要修改的文件是
~~scripts/background.js~~scripts/options.js

作者有考虑将这个打包成crx并上架扩展商店吗？这个工具很实用

**Comment by goldli** [comment]
这个本来就是用来学习如何开发扩展做的示例。 
如果要做好， 需要把这个扩展做成侧边栏，并且使用VUE来显示页面。
因为其它的原因，一直没有继续。
